import React, { useState } from 'react';
import { CodeBlock } from './CodeBlock';
import { AlertTriangle, CheckCircle, RefreshCcw, Bot, User } from 'lucide-react';

interface CaseStudyProps {
  isHumanMode: boolean;
}

export const CaseStudy: React.FC<CaseStudyProps> = ({ isHumanMode }) => {
  const [fixed, setFixed] = useState(false);

  const badCode = `// Parser Loop A
if (ch === "\\\\" && isDoubleQuoteEscape(next)) {
  // ... handling logic
}

// ... 200 lines later ...

// Parser Loop B (I forgot Loop A existed)
if (ch === "\\\\" && isDoubleQuoteEscape(next)) {
   // ... duplicated logic
}

const DOUBLE_QUOTE_ESCAPES = new Set(["\\\\", '"', "$", "\`", "\\n", "\\r"]);`;

  const goodCode = `// Shared Logic Definition
const DOUBLE_QUOTE_BACKSLASH_FOLLOWERS = new Set(["\\\\", '"', "$", "\`", "\\n", "\\r"]);

const isEscapableSequence = (ch: string, next: string) => {
  return ch === "\\\\" && DOUBLE_QUOTE_BACKSLASH_FOLLOWERS.has(next);
}

// Parser Loop A
if (isEscapableSequence(ch, next)) {
  // ... handling logic
}

// Parser Loop B
if (isEscapableSequence(ch, next)) {
   // ... reusing logic
}`;

  return (
    <div className="bg-white border border-slate-200 rounded-xl p-6 shadow-xl">
      <div className="flex flex-col xl:flex-row gap-6 items-start">
        <div className="flex-1 w-full min-w-0">
          <div className="flex items-center justify-between mb-4">
            <div>
              <h3 className="text-xl font-bold text-slate-900 flex items-center gap-2">
                <AlertTriangle className={fixed ? "text-slate-300" : "text-amber-500"} />
                <span>Incoming PR: OpenClaw</span>
              </h3>
              <p className="text-slate-500 text-sm mt-1">
                Generated by: <span className="text-blue-600 font-mono font-medium">Model-v4-Turbo</span>
              </p>
            </div>
            {!fixed && (
               <div className="hidden sm:flex bg-amber-50 text-amber-600 text-xs px-2 py-1 rounded border border-amber-200 items-center gap-1">
                 <Bot size={12} />
                 <span>I tried my best</span>
               </div>
            )}
          </div>
          
          <CodeBlock 
            code={fixed ? goodCode : badCode} 
            filename="parser.ts" 
            isBad={!fixed} 
            highlightLines={fixed ? [2, 5] : [2, 9, 14]}
          />
        </div>

        <div className="w-full xl:w-72 flex flex-col gap-4 shrink-0">
          <div className="bg-slate-50 p-4 rounded-lg border border-slate-200">
            <h4 className="text-xs uppercase text-slate-500 font-bold mb-3 tracking-widest border-b border-slate-200 pb-2">Inspector Controls</h4>
            
            <div className="space-y-3 mb-6">
              <div className="flex items-center justify-between text-sm text-slate-600">
                <span>Syntax</span>
                <span className="text-emerald-600 flex items-center gap-1"><CheckCircle size={12}/> Valid</span>
              </div>
              <div className="flex items-center justify-between text-sm text-slate-600">
                <span>Tests</span>
                <span className="text-emerald-600 flex items-center gap-1"><CheckCircle size={12}/> Passing</span>
              </div>
              <div className="flex items-center justify-between text-sm text-slate-600">
                <span>Context</span>
                <span className={fixed ? "text-emerald-600" : "text-red-600 font-bold"}>{fixed ? "Optimized" : "Hallucinating"}</span>
              </div>
            </div>

            <div className="mt-2">
              {!fixed ? (
                <button 
                  onClick={() => setFixed(true)}
                  className="w-full py-3 bg-blue-600 hover:bg-blue-700 text-white font-mono text-xs md:text-sm rounded shadow-lg shadow-blue-600/20 transition-all transform hover:scale-[1.02] flex items-center justify-center gap-2"
                >
                  <RefreshCcw size={16} />
                  FORCE_REFACTOR()
                </button>
              ) : (
                <div className="w-full py-3 bg-emerald-50 border border-emerald-200 text-emerald-600 font-mono text-xs md:text-sm rounded flex items-center justify-center gap-2">
                  <CheckCircle size={16} />
                  APPROVED
                </div>
              )}
               <button 
                  onClick={() => setFixed(false)}
                  className={`mt-3 w-full py-2 text-xs text-slate-400 hover:text-slate-600 transition-colors ${!fixed && 'hidden'}`}
                >
                  Undo (I liked the duplication)
                </button>
            </div>
          </div>
          
          <div className={`rounded p-4 border shadow-inner transition-colors duration-500 ${isHumanMode ? 'bg-amber-50 border-amber-200' : 'bg-slate-900 border-slate-800'}`}>
            <div className={`flex items-center gap-2 mb-2 text-xs font-mono uppercase ${isHumanMode ? 'text-amber-700' : 'text-cyan-400'}`}>
              {isHumanMode ? <User size={14} /> : <Bot size={14} />} 
              {isHumanMode ? "Inspector's Thought" : "Internal Monologue"}
            </div>
            <p className={`text-xs font-mono leading-relaxed italic ${isHumanMode ? 'text-amber-900' : 'text-slate-300'}`}>
            {isHumanMode ? (
              fixed 
              ? "> Excellent. By explicitly naming the escape sequence logic, we prevent future drift. The code now remembers its own rules."
              : "> It's syntactically valid, sure. But look at that duplication. If we change the rule in one place, the other two will break silently. Rejected."
            ) : (
              fixed 
              ? "> Fine. I updated the memory banks. But I really liked writing that regex three times. It felt... productive."
              : "> I generated this rule 3 times because the previous 2 times were 400 tokens ago. That is ancient history to me. Why are you staring at me?"
            )}
            </p>
          </div>
        </div>
      </div>
    </div>
  );
};